name: Run CI Tests
on: [push]
jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-22.04
          - macos-14
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-golang@v1
        with:
          version-file: go.mod
      - uses: extractions/setup-just@v2
      - name: Run Go Test
        run: |
          just test
